version: '3.4'

services:
    hadoop-slave1:
        image: mikaelsouza/atmosphere-hdfs:2.7.4.1
        container_name: hadoop-slave1
    hadoop-slave2:
        image: mikaelsouza/atmosphere-hdfs:2.7.4.1
        container_name: hadoop-slave2
    hadoop-slave3:
        image: mikaelsouza/atmosphere-hdfs:2.7.4.1
        container_name: hadoop-slave3
    hadoop-master:
        image: mikaelsouza/atmosphere-hdfs-master:2.7.4.1
        container_name: hadoop-master
        depends_on:
            - hadoop-slave1
            - hadoop-slave2
            - hadoop-slave3
        ports:
          - '8020:8020'
