version: '3.4'

services:
    vallum-db:
        image: ronnypeterson/vallum-db-test
        container_name: vallum-db
        environment:
          - MYSQL_ROOT_PASSWORD=#s3nh@#
    vallum:
        image: ronnypeterson/vallum-file-test
        container_name: vallum
        ports:
          - 9000:9000
        depends_on:
          - vallum-db
    client:
        image: mikaelsouza/atmosphere-client-secure
        container_name: client
        depends_on:
          - vallum